version: "3"

services:

  app:
    container_name: context_matching_backend
    build: .
    volumes:
      - .:/home/user/app
    ports:
      - ${PORT}:${PORT}
    command: ./run_server.sh
    environment:
      - PORT=${PORT}

networks:
  default:
    name: ${NETWORK_NAME}
    external: true
