name: Continous Deployment Actions Workflow

on:
  push:
    branches: [ "main" ]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_GITHUB }}
        path: 'repo'
    
    - name: Copy Files from repo to Server
      uses: garygrossgarten/github-action-scp@release
      with:
          local: repo
          remote: ../../datadrive/dev/context-matching/context_backend
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privatekey: ${{ secrets.key }}
          port: ${{secrets.PORT}}

    - name: Deloy on Linux VM via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}  # Public IPv4 DNS
        username: ${{ secrets.USERNAME }}  # ubuntu
        key: ${{ secrets.KEY }}  # SSH private key (sudo cat mykey.pem)
        port: ${{ secrets.PORT }} # 22 default
        script: |
         cd ~/../../datadrive/dev/context-matching/context_backend/
         sudo docker compose down
         chmod +x run_server.sh
         sudo docker compose up --build -d
          
